/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.api;

import java.util.ArrayList;
import java.util.List;

import com.kerbores.gitea.client.JSON;
import com.kerbores.gitea.client.model.Organization;
import com.kerbores.gitea.client.model.User;
import com.kerbores.gitea.client.request.AbstractApiClient;
import com.kerbores.gitea.client.request.Header;
import com.kerbores.gitea.client.request.Parameters;

public class AdminApi {

    AbstractApiClient apiClient;
    JSON json;

    public AdminApi(AbstractApiClient apiClient) {
        this.apiClient = apiClient;
        this.json = new JSON();
    }

    public List<Organization> listAllOrganizations(int page, int limit) {
        List<Organization> organizations = new ArrayList<>();
        return json.deserialize(apiClient.get("admin/orgs",
                                              Parameters.NEW()
                                                        .add("page", page)
                                                        .add("limit", limit),
                                              Header.NEW())

                                         .getContent(),
                                organizations.getClass());
    }

    public List<User> listAllUsers() {
        List<User> users = new ArrayList<>();
        return json.deserialize(apiClient.get("admin/users",
                                              Parameters.NEW(),
                                              Header.NEW())
                                         .getContent(),
                                users.getClass());
    }
}
