/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.api;

import java.util.List;

import com.kerbores.gitea.client.model.Organization;
import com.kerbores.gitea.client.model.User;
import com.kerbores.gitea.client.request.ApiClient;
import com.kerbores.gitea.client.request.Header;
import com.kerbores.gitea.client.request.Parameters;
import com.kerbores.gitea.client.request.Response;

public class AdminApi {

    ApiClient apiClient;

    public AdminApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public List<Organization> listAllOrganizations(int page, int limit) {
        Response response = apiClient.get("admin/orgs",
                                          Parameters.NEW()
                                                    .add("page", page)
                                                    .add("limit", limit),
                                          Header.NEW());
        return apiClient.deserializeAsList(apiClient.content(response), Organization.class);
    }

    public List<User> listAllUsers() {
        Response response = apiClient.get("admin/users",
                                          Parameters.NEW(),
                                          Header.NEW());
        return apiClient.deserializeAsList(apiClient.content(response), User.class);
    }
}
