/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.api;

import com.kerbores.gitea.client.request.ApiClient;

public class OrganizationApi {
    ApiClient apiClient;

    public OrganizationApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }
}
