/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client;

import java.util.List;

import org.nutz.json.Json;
import org.nutz.json.JsonFormat;

public class JsonUtils {
    
    public static String serialize(Object obj) {
        return Json.toJson(obj);
    }

    public static <T> T deserialize(String body, Class<T> clazz) {
        Json.setDefaultJsonformat(JsonFormat.full().setDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS Z"));
        T t = Json.fromJson(clazz, body);
        Json.setDefaultJsonformat(JsonFormat.full().setDateFormat("yyyy-MM-dd HH:mm:ss"));
        return t;
    }

    public static <T> List<T> deserializeAsList(String body, Class<T> clazz) {
        Json.setDefaultJsonformat(JsonFormat.full().setDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS Z"));
        List<T> ts = Json.fromJsonAsList(clazz, body);
        Json.setDefaultJsonformat(JsonFormat.full().setDateFormat("yyyy-MM-dd HH:mm:ss"));
        return ts;
    }

}
