/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.auth;

import java.io.UnsupportedEncodingException;
import java.util.Base64;
import java.util.Map;

public class HttpBasicAuth implements Authentication {
    private String username;
    private String password;

    public HttpBasicAuth(String username, String password) {
        this.username = username;
        this.password = password;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public void applyToHeader(Map<String, String> headerParams) {
        if (username == null && password == null) {
            return;
        }
        headerParams.put("Authorization",
                         basic(
                               username == null ? "" : username,
                               password == null ? "" : password));
    }

    public String basic(String userName, String password) {
        try {
            String usernameAndPassword = userName + ":" + password;
            byte[] bytes = usernameAndPassword.getBytes("ISO-8859-1");
            String encoded = Base64.getEncoder().encodeToString(bytes);
            return "Basic " + encoded;
        }
        catch (UnsupportedEncodingException e) {
            throw new AssertionError();
        }
    }
}
