/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import com.alibaba.fastjson.annotation.JSONField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * AnnotatedTag represents an annotated tag
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(of = "tag")
public class AnnotatedTag {
    @JSONField(name = "message")
    private String message;

    @JSONField(name = "object")
    private AnnotatedTagObject object;

    @JSONField(name = "sha")
    private String sha;

    @JSONField(name = "tag")
    private String tag;

    @JSONField(name = "tagger")
    private CommitUser tagger;

    @JSONField(name = "url")
    private String url;

    @JSONField(name = "verification")
    private PayloadCommitVerification verification;

}
