/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import org.nutz.json.JsonField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * AnnotatedTag represents an annotated tag
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(of = "tag")
public class AnnotatedTag {
    @JsonField("message")
    private String message;

    @JsonField("object")
    private AnnotatedTagObject object;

    @JsonField("sha")
    private String sha;

    @JsonField("tag")
    private String tag;

    @JsonField("tagger")
    private CommitUser tagger;

    @JsonField("url")
    private String url;

    @JsonField("verification")
    private PayloadCommitVerification verification;

}
