/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Attachment a generic attachment
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Attachment {
    @JSONField(name = "browser_download_url")
    private String browserDownloadUrl;

    @JSONField(name = "created_at")
    private Date createdAt;

    @JSONField(name = "download_count")
    private Long downloadCount;

    @JSONField(name = "id")
    private Long id;

    @JSONField(name = "name")
    private String name;

    @JSONField(name = "size")
    private Long size;

    @JSONField(name = "uuid")
    private String uuid;

}
