/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.util.Date;

import org.nutz.json.JsonField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Attachment a generic attachment
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Attachment {
    @JsonField("browser_download_url")
    private String browserDownloadUrl;

    @JsonField("created_at")
    private Date createdAt;

    @JsonField("download_count")
    private Long downloadCount;

    @JsonField("id")
    private Long id;

    @JsonField("name")
    private String name;

    @JsonField("size")
    private Long size;

    @JsonField("uuid")
    private String uuid;

}
