/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.util.List;

import com.alibaba.fastjson.annotation.JSONField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Branch represents a repository branch
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Branch {
    @JSONField(name = "commit")
    private PayloadCommit commit;

    @JSONField(name = "enable_status_check")
    private Boolean enableStatusCheck;

    @JSONField(name = "name")
    private String name;

    @JSONField(name = "protected")
    private Boolean _protected;

    @JSONField(name = "required_approvals")
    private Long requiredApprovals;

    @JSONField(name = "status_check_contexts")
    private List<String> statusCheckContexts;

    @JSONField(name = "user_can_merge")
    private Boolean userCanMerge;

    @JSONField(name = "user_can_push")
    private Boolean userCanPush;

}
