/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.util.List;

import com.alibaba.fastjson.annotation.JSONField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Commit
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Commit {
    @JSONField(name = "author")
    private User author;

    @JSONField(name = "commit")
    private RepoCommit commit;

    @JSONField(name = "committer")
    private User committer;

    @JSONField(name = "html_url")
    private String htmlUrl;

    @JSONField(name = "parents")
    private List<CommitMeta> parents;

    @JSONField(name = "sha")
    private String sha;

    @JSONField(name = "url")
    private String url;

}
