/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.time.OffsetDateTime;
import java.util.Date;

import org.nutz.json.JsonField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Comment represents a comment on a commit or issue
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Comment {
    @JsonField("body")
    private String body;

    @JsonField("created_at")
    private Date createdAt;

    @JsonField("html_url")
    private String htmlUrl;

    @JsonField("id")
    private Long id;

    @JsonField("issue_url")
    private String issueUrl;

    @JsonField("original_author")
    private String originalAuthor;

    @JsonField("original_author_id")
    private Long originalAuthorId;

    @JsonField("pull_request_url")
    private String pullRequestUrl;

    @JsonField("updated_at")
    private OffsetDateTime updatedAt;

    @JsonField("user")
    private User user;

}
