/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import com.alibaba.fastjson.annotation.JSONField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * ContentsResponse contains information about a repo&#39;s entry&#39;s (dir,
 * file, symlink, submodule) metadata and content
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ContentsResponse {
    @JSONField(name = "_links")
    private FileLinksResponse links;

    @JSONField(name = "content")
    private String content;

    @JSONField(name = "download_url")
    private String downloadUrl;

    @JSONField(name = "encoding")
    private String encoding;

    @JSONField(name = "git_url")
    private String gitUrl;

    @JSONField(name = "html_url")
    private String htmlUrl;

    @JSONField(name = "name")
    private String name;

    @JSONField(name = "path")
    private String path;

    @JSONField(name = "sha")
    private String sha;

    @JSONField(name = "size")
    private Long size;

    @JSONField(name = "submodule_git_url")
    private String submoduleGitUrl;

    @JSONField(name = "target")
    private String target;

    @JSONField(name = "type")
    private String type;

    @JSONField(name = "url")
    private String url;

}
