/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import org.nutz.json.JsonField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * ContentsResponse contains information about a repo&#39;s entry&#39;s (dir,
 * file, symlink, submodule) metadata and content
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ContentsResponse {
    @JsonField("_links")
    private FileLinksResponse links;

    @JsonField("content")
    private String content;

    @JsonField("download_url")
    private String downloadUrl;

    @JsonField("encoding")
    private String encoding;

    @JsonField("git_url")
    private String gitUrl;

    @JsonField("html_url")
    private String htmlUrl;

    @JsonField("name")
    private String name;

    @JsonField("path")
    private String path;

    @JsonField("sha")
    private String sha;

    @JsonField("size")
    private Long size;

    @JsonField("submodule_git_url")
    private String submoduleGitUrl;

    @JsonField("target")
    private String target;

    @JsonField("type")
    private String type;

    @JsonField("url")
    private String url;

}
