/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import org.nutz.json.JsonField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * CreateUserOption create user options
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CreateUserOption {
    @JsonField("email")
    private String email;

    @JsonField("full_name")
    private String fullName;

    @JsonField("login_name")
    private String loginName;

    @JsonField("must_change_password")
    private Boolean mustChangePassword;

    @JsonField("password")
    private String password;

    @JsonField("send_notify")
    private Boolean sendNotify;

    @JsonField("source_id")
    private Long sourceId;

    @JsonField("username")
    private String username;

}
