/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import com.alibaba.fastjson.annotation.JSONField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * CreateStatusOption holds the information needed to create a new Status for a
 * Commit
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CreateStatusOption {
    @JSONField(name = "context")
    private String context;

    @JSONField(name = "description")
    private String description;

    @JSONField(name = "state")
    private String state;

    @JSONField(name = "target_url")
    private String targetUrl;

}
