/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import org.nutz.json.JsonField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * CreateKeyOption options when creating a key
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CreateKeyOption {
    @JsonField("key")
    private String key;

    @JsonField("read_only")
    private Boolean readOnly;

    @JsonField("title")
    private String title;

}
