/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import org.nutz.json.JsonField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * CreateRepoOption options when creating repository
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CreateRepoOption {
    @JsonField("auto_init")
    private Boolean autoInit;

    @JsonField("description")
    private String description;

    @JsonField("gitignores")
    private String gitignores;

    @JsonField("issue_labels")
    private String issueLabels;

    @JsonField("license")
    private String license;

    @JsonField("name")
    private String name;

    @JsonField("private")
    private Boolean _private;

    @JsonField("readme")
    private String readme;

}
