/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.util.List;

import org.nutz.json.JsonField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * CreateHookOption options when create a hook
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CreateHookOption {
    @JsonField("active")
    private boolean active;

    @JsonField("branch_filter")
    private String branchFilter;

    @JsonField("config")
    private CreateHookOptionConfig config;

    @JsonField("events")
    private List<String> events;

    /**
     * Gets or Sets type
     */
    public enum TypeEnum {
        DINGTALK("dingtalk"),

        DISCORD("discord"),

        GITEA("gitea"),

        GOGS("gogs"),

        MSTEAMS("msteams"),

        SLACK("slack"),

        TELEGRAM("telegram");

        private String value;

        TypeEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static TypeEnum fromValue(String text) {
            for (TypeEnum b : TypeEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }

    }

    @JsonField("type")
    private TypeEnum type;

}
