/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import org.nutz.json.JsonField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * CreateStatusOption holds the information needed to create a new Status for a
 * Commit
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CreateStatusOption {
    @JsonField("context")
    private String context;

    @JsonField("description")
    private String description;

    @JsonField("state")
    private String state;

    @JsonField("target_url")
    private String targetUrl;

}
