/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import com.alibaba.fastjson.annotation.JSONField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * CreateUserOption create user options
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CreateUserOption {
    @JSONField(name = "email")
    private String email;

    @JSONField(name = "full_name")
    private String fullName;

    @JSONField(name = "login_name")
    private String loginName;

    @JSONField(name = "must_change_password")
    private Boolean mustChangePassword;

    @JSONField(name = "password")
    private String password;

    @JSONField(name = "send_notify")
    private Boolean sendNotify;

    @JSONField(name = "source_id")
    private Long sourceId;

    @JSONField(name = "username")
    private String username;

}
