/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import com.alibaba.fastjson.annotation.JSONField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * CreateRepoOption options when creating repository
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CreateRepoOption {
    @JSONField(name = "auto_init")
    private Boolean autoInit;

    @JSONField(name = "description")
    private String description;

    @JSONField(name = "gitignores")
    private String gitignores;

    @JSONField(name = "issue_labels")
    private String issueLabels;

    @JSONField(name = "license")
    private String license;

    @JSONField(name = "name")
    private String name;

    @JSONField(name = "private")
    private Boolean _private;

    @JSONField(name = "readme")
    private String readme;

}
