/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.util.HashMap;

/**
 * CreateHookOptionConfig has all config options in it required are
 * \&quot;content_type\&quot; and \&quot;url\&quot; Required
 */
public class CreateHookOptionConfig extends HashMap<String, String> {

    private static final long serialVersionUID = 1L;

}
