/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import com.alibaba.fastjson.annotation.JSONField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * EditOrgOption options for editing an organization
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class EditOrgOption {
    @JSONField(name = "description")
    private String description;

    @JSONField(name = "full_name")
    private String fullName;

    @JSONField(name = "location")
    private String location;

    @JSONField(name = "repo_admin_change_team_access")
    private Boolean repoAdminChangeTeamAccess;

    /**
     * possible values are &#x60;public&#x60;, &#x60;limited&#x60; or
     * &#x60;private&#x60;
     */
    public enum VisibilityEnum {
        PUBLIC("public"),

        LIMITED("limited"),

        PRIVATE("private");

        private String value;

        VisibilityEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static VisibilityEnum fromValue(String text) {
            for (VisibilityEnum b : VisibilityEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }

    }

    @JSONField(name = "visibility")
    private VisibilityEnum visibility;

    @JSONField(name = "website")
    private String website;

}
