/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import org.nutz.json.JsonField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * EditRepoOption options when editing a repository&#39;s properties
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class EditRepoOption {
    @JsonField("allow_merge_commits")
    private Boolean allowMergeCommits;

    @JsonField("allow_rebase")
    private Boolean allowRebase;

    @JsonField("allow_rebase_explicit")
    private Boolean allowRebaseExplicit;

    @JsonField("allow_squash_merge")
    private Boolean allowSquashMerge;

    @JsonField("archived")
    private Boolean archived;

    @JsonField("default_branch")
    private String defaultBranch;

    @JsonField("description")
    private String description;

    @JsonField("external_tracker")
    private ExternalTracker externalTracker;

    @JsonField("external_wiki")
    private ExternalWiki externalWiki;

    @JsonField("has_issues")
    private Boolean hasIssues;

    @JsonField("has_pull_requests")
    private Boolean hasPullRequests;

    @JsonField("has_wiki")
    private Boolean hasWiki;

    @JsonField("ignore_whitespace_conflicts")
    private Boolean ignoreWhitespaceConflicts;

    @JsonField("internal_tracker")
    private InternalTracker internalTracker;

    @JsonField("name")
    private String name;

    @JsonField("private")
    private Boolean _private;

    @JsonField("template")
    private Boolean template;

    @JsonField("website")
    private String website;

}
