/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.util.Date;

import org.nutz.json.JsonField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * EditMilestoneOption options for editing a milestone
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class EditMilestoneOption {
    @JsonField("description")
    private String description;

    @JsonField("due_on")
    private Date dueOn;

    @JsonField("state")
    private String state;

    @JsonField("title")
    private String title;

}
