/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.util.Date;
import java.util.List;

import com.alibaba.fastjson.annotation.JSONField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * EditIssueOption options for editing an issue
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class EditIssueOption {
    @JSONField(name = "assignee")
    private String assignee;

    @JSONField(name = "assignees")
    private List<String> assignees;

    @JSONField(name = "body")
    private String body;

    @JSONField(name = "due_date")
    private Date dueDate;

    @JSONField(name = "milestone")
    private Long milestone;

    @JSONField(name = "state")
    private String state;

    @JSONField(name = "title")
    private String title;

    @JSONField(name = "unset_due_date")
    private Boolean unsetDueDate;

}
