/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import com.alibaba.fastjson.annotation.JSONField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * EditReleaseOption options when editing a release
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class EditReleaseOption {
    @JSONField(name = "body")
    private String body;

    @JSONField(name = "draft")
    private Boolean draft;

    @JSONField(name = "name")
    private String name;

    @JSONField(name = "prerelease")
    private Boolean prerelease;

    @JSONField(name = "tag_name")
    private String tagName;

    @JSONField(name = "target_commitish")
    private String targetCommitish;

}
