/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.util.Date;
import java.util.List;

import org.nutz.json.JsonField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * EditIssueOption options for editing an issue
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class EditIssueOption {
    @JsonField("assignee")
    private String assignee;

    @JsonField("assignees")
    private List<String> assignees;

    @JsonField("body")
    private String body;

    @JsonField("due_date")
    private Date dueDate;

    @JsonField("milestone")
    private Long milestone;

    @JsonField("state")
    private String state;

    @JsonField("title")
    private String title;

    @JsonField("unset_due_date")
    private Boolean unsetDueDate;

}
