/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import org.nutz.json.JsonField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * EditUserOption edit user options
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class EditUserOption {
    @JsonField("active")
    private Boolean active;

    @JsonField("admin")
    private Boolean admin;

    @JsonField("allow_create_organization")
    private Boolean allowCreateOrganization;

    @JsonField("allow_git_hook")
    private Boolean allowGitHook;

    @JsonField("allow_import_local")
    private Boolean allowImportLocal;

    @JsonField("email")
    private String email;

    @JsonField("full_name")
    private String fullName;

    @JsonField("location")
    private String location;

    @JsonField("login_name")
    private String loginName;

    @JsonField("max_repo_creation")
    private Long maxRepoCreation;

    @JsonField("must_change_password")
    private Boolean mustChangePassword;

    @JsonField("password")
    private String password;

    @JsonField("prohibit_login")
    private Boolean prohibitLogin;

    @JsonField("source_id")
    private Long sourceId;

    @JsonField("website")
    private String website;

}
