/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import com.alibaba.fastjson.annotation.JSONField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * EditUserOption edit user options
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class EditUserOption {
    @JSONField(name = "active")
    private Boolean active;

    @JSONField(name = "admin")
    private Boolean admin;

    @JSONField(name = "allow_create_organization")
    private Boolean allowCreateOrganization;

    @JSONField(name = "allow_git_hook")
    private Boolean allowGitHook;

    @JSONField(name = "allow_import_local")
    private Boolean allowImportLocal;

    @JSONField(name = "email")
    private String email;

    @JSONField(name = "full_name")
    private String fullName;

    @JSONField(name = "location")
    private String location;

    @JSONField(name = "login_name")
    private String loginName;

    @JSONField(name = "max_repo_creation")
    private Long maxRepoCreation;

    @JSONField(name = "must_change_password")
    private Boolean mustChangePassword;

    @JSONField(name = "password")
    private String password;

    @JSONField(name = "prohibit_login")
    private Boolean prohibitLogin;

    @JSONField(name = "source_id")
    private Long sourceId;

    @JSONField(name = "website")
    private String website;

}
