/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.util.List;
import java.util.Map;

import com.alibaba.fastjson.annotation.JSONField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * EditHookOption options when modify one hook
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class EditHookOption {
    @JSONField(name = "active")
    private Boolean active;

    @JSONField(name = "branch_filter")
    private String branchFilter;

    @JSONField(name = "config")
    private Map<String, String> config;

    @JSONField(name = "events")
    private List<String> events;

}
