/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import com.alibaba.fastjson.annotation.JSONField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * EditRepoOption options when editing a repository&#39;s properties
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class EditRepoOption {
    @JSONField(name = "allow_merge_commits")
    private Boolean allowMergeCommits;

    @JSONField(name = "allow_rebase")
    private Boolean allowRebase;

    @JSONField(name = "allow_rebase_explicit")
    private Boolean allowRebaseExplicit;

    @JSONField(name = "allow_squash_merge")
    private Boolean allowSquashMerge;

    @JSONField(name = "archived")
    private Boolean archived;

    @JSONField(name = "default_branch")
    private String defaultBranch;

    @JSONField(name = "description")
    private String description;

    @JSONField(name = "external_tracker")
    private ExternalTracker externalTracker;

    @JSONField(name = "external_wiki")
    private ExternalWiki externalWiki;

    @JSONField(name = "has_issues")
    private Boolean hasIssues;

    @JSONField(name = "has_pull_requests")
    private Boolean hasPullRequests;

    @JSONField(name = "has_wiki")
    private Boolean hasWiki;

    @JSONField(name = "ignore_whitespace_conflicts")
    private Boolean ignoreWhitespaceConflicts;

    @JSONField(name = "internal_tracker")
    private InternalTracker internalTracker;

    @JSONField(name = "name")
    private String name;

    @JSONField(name = "private")
    private Boolean _private;

    @JSONField(name = "template")
    private Boolean template;

    @JSONField(name = "website")
    private String website;

}
