/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import org.nutz.json.JsonField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * EditReleaseOption options when editing a release
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class EditReleaseOption {
    @JsonField("body")
    private String body;

    @JsonField("draft")
    private Boolean draft;

    @JsonField("name")
    private String name;

    @JsonField("prerelease")
    private Boolean prerelease;

    @JsonField("tag_name")
    private String tagName;

    @JsonField("target_commitish")
    private String targetCommitish;

}
