/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import com.alibaba.fastjson.annotation.JSONField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Email an email address belonging to a user
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Email {
    @JSONField(name = "email")
    private String email;

    @JSONField(name = "primary")
    private Boolean primary;

    @JSONField(name = "verified")
    private Boolean verified;

}
