/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import com.alibaba.fastjson.annotation.JSONField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * GitBlobResponse represents a git blob
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class GitBlobResponse {
    @JSONField(name = "content")
    private String content;

    @JSONField(name = "encoding")
    private String encoding;

    @JSONField(name = "sha")
    private String sha;

    @JSONField(name = "size")
    private Long size;

    @JSONField(name = "url")
    private String url;

}
