/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import org.nutz.json.JsonField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * GitHook represents a Git repository hook
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class GitHook {
    @JsonField("content")
    private String content;

    @JsonField("is_active")
    private Boolean isActive;

    @JsonField("name")
    private String name;

}
