/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.util.List;

import org.nutz.json.JsonField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * GitTreeResponse returns a git tree
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class GitTreeResponse {
    @JsonField("page")
    private Long page;

    @JsonField("sha")
    private String sha;

    @JsonField("total_count")
    private Long totalCount;

    @JsonField("tree")
    private List<GitEntry> tree;

    @JsonField("truncated")
    private Boolean truncated;

    @JsonField("url")
    private String url;

}
