/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.util.Date;
import java.util.List;

import org.nutz.json.JsonField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * GPGKey a user GPG key to sign commit and tag in repository
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class GPGKey {
    @JsonField("can_certify")
    private Boolean canCertify;

    @JsonField("can_encrypt_comms")
    private Boolean canEncryptComms;

    @JsonField("can_encrypt_storage")
    private Boolean canEncryptStorage;

    @JsonField("can_sign")
    private Boolean canSign;

    @JsonField("created_at")
    private Date createdAt;

    @JsonField("emails")
    private List<GPGKeyEmail> emails;

    @JsonField("expires_at")
    private Date expiresAt;

    @JsonField("id")
    private Long id;

    @JsonField("key_id")
    private String keyId;

    @JsonField("primary_key_id")
    private String primaryKeyId;

    @JsonField("public_key")
    private String publicKey;

    @JsonField("subkeys")
    private List<GPGKey> subkeys;

}
