/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.util.Date;
import java.util.List;
import java.util.Map;

import com.alibaba.fastjson.annotation.JSONField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Hook a hook is a web hook when one repository changed
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Hook {
    @JSONField(name = "active")
    private Boolean active;

    @JSONField(name = "config")
    private Map<String, String> config;

    @JSONField(name = "created_at")
    private Date createdAt;

    @JSONField(name = "events")
    private List<String> events;

    @JSONField(name = "id")
    private Long id;

    @JSONField(name = "type")
    private String type;

    @JSONField(name = "updated_at")
    private Date updatedAt;

}
