/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.nutz.json.JsonField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Hook a hook is a web hook when one repository changed
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Hook {
    @JsonField("active")
    private Boolean active;

    @JsonField("config")
    private Map<String, String> config;

    @JsonField("created_at")
    private Date createdAt;

    @JsonField("events")
    private List<String> events;

    @JsonField("id")
    private Long id;

    @JsonField("type")
    private String type;

    @JsonField("updated_at")
    private Date updatedAt;

}
