/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import com.alibaba.fastjson.annotation.JSONField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Identity for a person&#39;s identity like an author or committer
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Identity {
    @JSONField(name = "email")
    private String email;

    @JSONField(name = "name")
    private String name;

}
