/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import org.nutz.json.JsonField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * InternalTracker represents settings for internal tracker
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class InternalTracker {
    @JsonField("allow_only_contributors_to_track_time")
    private Boolean allowOnlyContributorsToTrackTime;

    @JsonField("enable_issue_dependencies")
    private Boolean enableIssueDependencies;

    @JsonField("enable_time_tracker")
    private Boolean enableTimeTracker;

}
