/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import com.alibaba.fastjson.annotation.JSONField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * InternalTracker represents settings for internal tracker
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class InternalTracker {
    @JSONField(name = "allow_only_contributors_to_track_time")
    private Boolean allowOnlyContributorsToTrackTime;

    @JSONField(name = "enable_issue_dependencies")
    private Boolean enableIssueDependencies;

    @JSONField(name = "enable_time_tracker")
    private Boolean enableTimeTracker;

}
