/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.time.OffsetDateTime;
import java.util.Date;
import java.util.List;

import org.nutz.json.JsonField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Issue represents an issue in a repository
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Issue {
    @JsonField("assignee")
    private User assignee;

    @JsonField("assignees")
    private List<User> assignees;

    @JsonField("body")
    private String body;

    @JsonField("closed_at")
    private Date closedAt;

    @JsonField("comments")
    private Long comments;

    @JsonField("created_at")
    private Date createdAt;

    @JsonField("due_date")
    private Date dueDate;

    @JsonField("html_url")
    private String htmlUrl;

    @JsonField("id")
    private Long id;

    @JsonField("labels")
    private List<Label> labels;

    @JsonField("milestone")
    private Milestone milestone;

    @JsonField("number")
    private Long number;

    @JsonField("original_author")
    private String originalAuthor;

    @JsonField("original_author_id")
    private Long originalAuthorId;

    @JsonField("pull_request")
    private PullRequestMeta pullRequest;

    @JsonField("repository")
    private RepositoryMeta repository;

    @JsonField("state")
    private String state;

    @JsonField("title")
    private String title;

    @JsonField("updated_at")
    private OffsetDateTime updatedAt;

    @JsonField("url")
    private String url;

    @JsonField("user")
    private User user;

}
