/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import org.nutz.json.JsonField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Label a label to an issue or a pr
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Label {
    @JsonField("color")
    private String color;

    @JsonField("description")
    private String description;

    @JsonField("id")
    private Long id;

    @JsonField("name")
    private String name;

    @JsonField("url")
    private String url;

}
