/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import com.alibaba.fastjson.annotation.JSONField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * MarkdownOption markdown options
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class MarkdownOption {
    @JSONField(name = "Context")
    private String context;

    @JSONField(name = "Mode")
    private String mode;

    @JSONField(name = "Text")
    private String text;

    @JSONField(name = "Wiki")
    private Boolean wiki;

}
