/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import org.nutz.json.JsonField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * MergePullRequestForm form for merging Pull Request
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class MergePullRequestOption {
    /**
     * Gets or Sets _do
     */
    public enum DoEnum {
        MERGE("merge"),

        REBASE("rebase"),

        REBASE_MERGE("rebase-merge"),

        SQUASH("squash");

        private String value;

        DoEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static DoEnum fromValue(String text) {
            for (DoEnum b : DoEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }

    }

    @JsonField("Do")
    private DoEnum _do;

    @JsonField("MergeMessageField")
    private String mergeMessageField;

    @JsonField("MergeTitleField")
    private String mergeTitleField;

}
