/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import org.nutz.json.JsonField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * MigrateRepoForm form for migrating repository
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class MigrateRepoForm {
    @JsonField("auth_password")
    private String authPassword;

    @JsonField("auth_username")
    private String authUsername;

    @JsonField("clone_addr")
    private String cloneAddr;

    @JsonField("description")
    private String description;

    @JsonField("issues")
    private Boolean issues;

    @JsonField("labels")
    private Boolean labels;

    @JsonField("milestones")
    private Boolean milestones;

    @JsonField("mirror")
    private Boolean mirror;

    @JsonField("private")
    private Boolean _private;

    @JsonField("pull_requests")
    private Boolean pullRequests;

    @JsonField("releases")
    private Boolean releases;

    @JsonField("repo_name")
    private String repoName;

    @JsonField("uid")
    private Long uid;

    @JsonField("wiki")
    private Boolean wiki;

}
