/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Milestone milestone is a collection of issues on one repository
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Milestone {
    @JSONField(name = "closed_at")
    private Date closedAt;

    @JSONField(name = "closed_issues")
    private Long closedIssues;

    @JSONField(name = "description")
    private String description;

    @JSONField(name = "due_on")
    private Date dueOn;

    @JSONField(name = "id")
    private Long id;

    @JSONField(name = "open_issues")
    private Long openIssues;

    @JSONField(name = "state")
    private String state;

    @JSONField(name = "title")
    private String title;

}
