/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import com.alibaba.fastjson.annotation.JSONField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * Organization represents an organization
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(of = "id")
public class Organization {
    @JSONField(name = "avatar_url")
    private String avatarUrl;

    @JSONField(name = "description")
    private String description;

    @JSONField(name = "full_name")
    private String fullName;

    @JSONField(name = "id")
    private long id;

    @JSONField(name = "location")
    private String location;

    @JSONField(name = "repo_admin_change_team_access")
    private boolean repoAdminChangeTeamAccess;

    @JSONField(name = "username")
    private String username;

    @JSONField(name = "visibility")
    private String visibility;

    @JSONField(name = "website")
    private String website;

}
