/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import org.nutz.json.JsonField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * Organization represents an organization
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(of = "id")
public class Organization {
    @JsonField("avatar_url")
    private String avatarUrl;

    @JsonField("description")
    private String description;

    @JsonField("full_name")
    private String fullName;

    @JsonField("id")
    private long id;

    @JsonField("location")
    private String location;

    @JsonField("repo_admin_change_team_access")
    private boolean repoAdminChangeTeamAccess;

    @JsonField("username")
    private String username;

    @JsonField("visibility")
    private String visibility;

    @JsonField("website")
    private String website;

}
