/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import org.nutz.json.JsonField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * PRBranchInfo information about a branch
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PRBranchInfo {
    @JsonField("label")
    private String label;

    @JsonField("ref")
    private String ref;

    @JsonField("repo")
    private Repository repo;

    @JsonField("repo_id")
    private Long repoId;

    @JsonField("sha")
    private String sha;

}
