/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.util.Date;

import org.nutz.json.JsonField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * PublicKey publickey is a user key to push code to repository
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PublicKey {
    @JsonField("created_at")
    private Date createdAt;

    @JsonField("fingerprint")
    private String fingerprint;

    @JsonField("id")
    private Long id;

    @JsonField("key")
    private String key;

    @JsonField("key_type")
    private String keyType;

    @JsonField("read_only")
    private Boolean readOnly;

    @JsonField("title")
    private String title;

    @JsonField("url")
    private String url;

    @JsonField("user")
    private User user;

}
