/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * PublicKey publickey is a user key to push code to repository
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PublicKey {
    @JSONField(name = "created_at")
    private Date createdAt;

    @JSONField(name = "fingerprint")
    private String fingerprint;

    @JSONField(name = "id")
    private Long id;

    @JSONField(name = "key")
    private String key;

    @JSONField(name = "key_type")
    private String keyType;

    @JSONField(name = "read_only")
    private Boolean readOnly;

    @JSONField(name = "title")
    private String title;

    @JSONField(name = "url")
    private String url;

    @JSONField(name = "user")
    private User user;

}
