/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.time.OffsetDateTime;
import java.util.Date;
import java.util.List;

import com.alibaba.fastjson.annotation.JSONField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * PullRequest represents a pull request
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PullRequest {
    @JSONField(name = "assignee")
    private User assignee;

    @JSONField(name = "assignees")
    private List<User> assignees;

    @JSONField(name = "base")
    private PRBranchInfo base;

    @JSONField(name = "body")
    private String body;

    @JSONField(name = "closed_at")
    private Date closedAt;

    @JSONField(name = "comments")
    private Long comments;

    @JSONField(name = "created_at")
    private Date createdAt;

    @JSONField(name = "diff_url")
    private String diffUrl;

    @JSONField(name = "due_date")
    private OffsetDateTime dueDate;

    @JSONField(name = "head")
    private PRBranchInfo head;

    @JSONField(name = "html_url")
    private String htmlUrl;

    @JSONField(name = "id")
    private Long id;

    @JSONField(name = "labels")
    private List<Label> labels;

    @JSONField(name = "merge_base")
    private String mergeBase;

    @JSONField(name = "merge_commit_sha")
    private String mergeCommitSha;

    @JSONField(name = "mergeable")
    private Boolean mergeable;

    @JSONField(name = "merged")
    private Boolean merged;

    @JSONField(name = "merged_at")
    private OffsetDateTime mergedAt;

    @JSONField(name = "merged_by")
    private User mergedBy;

    @JSONField(name = "milestone")
    private Milestone milestone;

    @JSONField(name = "number")
    private Long number;

    @JSONField(name = "patch_url")
    private String patchUrl;

    @JSONField(name = "state")
    private String state;

    @JSONField(name = "title")
    private String title;

    @JSONField(name = "updated_at")
    private OffsetDateTime updatedAt;

    @JSONField(name = "url")
    private String url;

    @JSONField(name = "user")
    private User user;

}
