/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.time.OffsetDateTime;
import java.util.Date;
import java.util.List;

import org.nutz.json.JsonField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * PullRequest represents a pull request
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PullRequest {
    @JsonField("assignee")
    private User assignee;

    @JsonField("assignees")
    private List<User> assignees;

    @JsonField("base")
    private PRBranchInfo base;

    @JsonField("body")
    private String body;

    @JsonField("closed_at")
    private Date closedAt;

    @JsonField("comments")
    private Long comments;

    @JsonField("created_at")
    private Date createdAt;

    @JsonField("diff_url")
    private String diffUrl;

    @JsonField("due_date")
    private OffsetDateTime dueDate;

    @JsonField("head")
    private PRBranchInfo head;

    @JsonField("html_url")
    private String htmlUrl;

    @JsonField("id")
    private Long id;

    @JsonField("labels")
    private List<Label> labels;

    @JsonField("merge_base")
    private String mergeBase;

    @JsonField("merge_commit_sha")
    private String mergeCommitSha;

    @JsonField("mergeable")
    private Boolean mergeable;

    @JsonField("merged")
    private Boolean merged;

    @JsonField("merged_at")
    private OffsetDateTime mergedAt;

    @JsonField("merged_by")
    private User mergedBy;

    @JsonField("milestone")
    private Milestone milestone;

    @JsonField("number")
    private Long number;

    @JsonField("patch_url")
    private String patchUrl;

    @JsonField("state")
    private String state;

    @JsonField("title")
    private String title;

    @JsonField("updated_at")
    private OffsetDateTime updatedAt;

    @JsonField("url")
    private String url;

    @JsonField("user")
    private User user;

}
