/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Reaction contain one reaction
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Reaction {
    @JSONField(name = "content")
    private String content;

    @JSONField(name = "created_at")
    private Date createdAt;

    @JSONField(name = "user")
    private User user;

}
