/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.time.OffsetDateTime;
import java.util.Date;
import java.util.List;

import org.nutz.json.JsonField;

import io.swagger.annotations.ApiModel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Release represents a repository release
 */
@ApiModel(description = "Release represents a repository release")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Release {
    @JsonField("assets")
    private List<Attachment> assets;

    @JsonField("author")
    private User author;

    @JsonField("body")
    private String body;

    @JsonField("created_at")
    private Date createdAt;

    @JsonField("draft")
    private Boolean draft;

    @JsonField("id")
    private Long id;

    @JsonField("name")
    private String name;

    @JsonField("prerelease")
    private Boolean prerelease;

    @JsonField("published_at")
    private OffsetDateTime publishedAt;

    @JsonField("tag_name")
    private String tagName;

    @JsonField("tarball_url")
    private String tarballUrl;

    @JsonField("target_commitish")
    private String targetCommitish;

    @JsonField("url")
    private String url;

    @JsonField("zipball_url")
    private String zipballUrl;

}
