/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import com.alibaba.fastjson.annotation.JSONField;

import io.swagger.annotations.ApiModel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * RepositoryMeta basic repository information
 */
@ApiModel(description = "RepositoryMeta basic repository information")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class RepositoryMeta {
    @JSONField(name = "full_name")
    private String fullName;

    @JSONField(name = "id")
    private Long id;

    @JSONField(name = "name")
    private String name;

}
