/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.time.OffsetDateTime;
import java.util.Date;

import org.nutz.json.JsonField;

import io.swagger.annotations.ApiModel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Repository represents a repository
 */
@ApiModel(description = "Repository represents a repository")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Repository {
    @JsonField("allow_merge_commits")
    private Boolean allowMergeCommits;

    @JsonField("allow_rebase")
    private Boolean allowRebase;

    @JsonField("allow_rebase_explicit")
    private Boolean allowRebaseExplicit;

    @JsonField("allow_squash_merge")
    private Boolean allowSquashMerge;

    @JsonField("archived")
    private Boolean archived;

    @JsonField("avatar_url")
    private String avatarUrl;

    @JsonField("clone_url")
    private String cloneUrl;

    @JsonField("created_at")
    private Date createdAt;

    @JsonField("default_branch")
    private String defaultBranch;

    @JsonField("description")
    private String description;

    @JsonField("empty")
    private Boolean empty;

    @JsonField("external_tracker")
    private ExternalTracker externalTracker;

    @JsonField("external_wiki")
    private ExternalWiki externalWiki;

    @JsonField("fork")
    private Boolean fork;

    @JsonField("forks_count")
    private Long forksCount;

    @JsonField("full_name")
    private String fullName;

    @JsonField("has_issues")
    private Boolean hasIssues;

    @JsonField("has_pull_requests")
    private Boolean hasPullRequests;

    @JsonField("has_wiki")
    private Boolean hasWiki;

    @JsonField("html_url")
    private String htmlUrl;

    @JsonField("id")
    private Long id;

    @JsonField("ignore_whitespace_conflicts")
    private Boolean ignoreWhitespaceConflicts;

    @JsonField("internal_tracker")
    private InternalTracker internalTracker;

    @JsonField("mirror")
    private Boolean mirror;

    @JsonField("name")
    private String name;

    @JsonField("open_issues_count")
    private Long openIssuesCount;

    @JsonField("open_pr_counter")
    private Long openPrCounter;

    @JsonField("original_url")
    private String originalUrl;

    @JsonField("owner")
    private User owner;

    @JsonField("parent")
    private Repository parent;

    @JsonField("permissions")
    private Permission permissions;

    @JsonField("private")
    private Boolean _private;

    @JsonField("release_counter")
    private Long releaseCounter;

    @JsonField("size")
    private Long size;

    @JsonField("ssh_url")
    private String sshUrl;

    @JsonField("stars_count")
    private Long starsCount;

    @JsonField("template")
    private Boolean template;

    @JsonField("updated_at")
    private OffsetDateTime updatedAt;

    @JsonField("watchers_count")
    private Long watchersCount;

    @JsonField("website")
    private String website;

}
