/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.time.OffsetDateTime;
import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;

import io.swagger.annotations.ApiModel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Repository represents a repository
 */
@ApiModel(description = "Repository represents a repository")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Repository {
    @JSONField(name = "allow_merge_commits")
    private Boolean allowMergeCommits;

    @JSONField(name = "allow_rebase")
    private Boolean allowRebase;

    @JSONField(name = "allow_rebase_explicit")
    private Boolean allowRebaseExplicit;

    @JSONField(name = "allow_squash_merge")
    private Boolean allowSquashMerge;

    @JSONField(name = "archived")
    private Boolean archived;

    @JSONField(name = "avatar_url")
    private String avatarUrl;

    @JSONField(name = "clone_url")
    private String cloneUrl;

    @JSONField(name = "created_at")
    private Date createdAt;

    @JSONField(name = "default_branch")
    private String defaultBranch;

    @JSONField(name = "description")
    private String description;

    @JSONField(name = "empty")
    private Boolean empty;

    @JSONField(name = "external_tracker")
    private ExternalTracker externalTracker;

    @JSONField(name = "external_wiki")
    private ExternalWiki externalWiki;

    @JSONField(name = "fork")
    private Boolean fork;

    @JSONField(name = "forks_count")
    private Long forksCount;

    @JSONField(name = "full_name")
    private String fullName;

    @JSONField(name = "has_issues")
    private Boolean hasIssues;

    @JSONField(name = "has_pull_requests")
    private Boolean hasPullRequests;

    @JSONField(name = "has_wiki")
    private Boolean hasWiki;

    @JSONField(name = "html_url")
    private String htmlUrl;

    @JSONField(name = "id")
    private Long id;

    @JSONField(name = "ignore_whitespace_conflicts")
    private Boolean ignoreWhitespaceConflicts;

    @JSONField(name = "internal_tracker")
    private InternalTracker internalTracker;

    @JSONField(name = "mirror")
    private Boolean mirror;

    @JSONField(name = "name")
    private String name;

    @JSONField(name = "open_issues_count")
    private Long openIssuesCount;

    @JSONField(name = "open_pr_counter")
    private Long openPrCounter;

    @JSONField(name = "original_url")
    private String originalUrl;

    @JSONField(name = "owner")
    private User owner;

    @JSONField(name = "parent")
    private Repository parent;

    @JSONField(name = "permissions")
    private Permission permissions;

    @JSONField(name = "private")
    private Boolean _private;

    @JSONField(name = "release_counter")
    private Long releaseCounter;

    @JSONField(name = "size")
    private Long size;

    @JSONField(name = "ssh_url")
    private String sshUrl;

    @JSONField(name = "stars_count")
    private Long starsCount;

    @JSONField(name = "template")
    private Boolean template;

    @JSONField(name = "updated_at")
    private OffsetDateTime updatedAt;

    @JSONField(name = "watchers_count")
    private Long watchersCount;

    @JSONField(name = "website")
    private String website;

}
