/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.util.List;

import com.alibaba.fastjson.annotation.JSONField;

import io.swagger.annotations.ApiModel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * SearchResults results of a successful search
 */
@ApiModel(description = "SearchResults results of a successful search")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SearchResults {
    @JSONField(name = "data")
    private List<Repository> data;

    @JSONField(name = "ok")
    private Boolean ok;

}
