/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.time.OffsetDateTime;
import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;

import io.swagger.annotations.ApiModel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Status holds a single Status of a single Commit
 */
@ApiModel(description = "Status holds a single Status of a single Commit")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Status {
    @JSONField(name = "context")
    private String context;

    @JSONField(name = "created_at")
    private Date createdAt;

    @JSONField(name = "creator")
    private User creator;

    @JSONField(name = "description")
    private String description;

    @JSONField(name = "id")
    private Long id;

    @JSONField(name = "status")
    private String status;

    @JSONField(name = "target_url")
    private String targetUrl;

    @JSONField(name = "updated_at")
    private OffsetDateTime updatedAt;

    @JSONField(name = "url")
    private String url;

}
