/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.time.OffsetDateTime;
import java.util.Date;

import org.nutz.json.JsonField;

import io.swagger.annotations.ApiModel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Status holds a single Status of a single Commit
 */
@ApiModel(description = "Status holds a single Status of a single Commit")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Status {
    @JsonField("context")
    private String context;

    @JsonField("created_at")
    private Date createdAt;

    @JsonField("creator")
    private User creator;

    @JsonField("description")
    private String description;

    @JsonField("id")
    private Long id;

    @JsonField("status")
    private String status;

    @JsonField("target_url")
    private String targetUrl;

    @JsonField("updated_at")
    private OffsetDateTime updatedAt;

    @JsonField("url")
    private String url;

}
