/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;

import io.swagger.annotations.ApiModel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * StopWatch represent a running stopwatch
 */
@ApiModel(description = "StopWatch represent a running stopwatch")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class StopWatch {
    @JSONField(name = "created")
    private Date created;

    @JSONField(name = "issue_index")
    private Long issueIndex;

}
