/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import org.nutz.json.JsonField;

import io.swagger.annotations.ApiModel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Tag represents a repository tag
 */
@ApiModel(description = "Tag represents a repository tag")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Tag {
    @JsonField("commit")
    private CommitMeta commit;

    @JsonField("id")
    private String id;

    @JsonField("name")
    private String name;

    @JsonField("tarball_url")
    private String tarballUrl;

    @JsonField("zipball_url")
    private String zipballUrl;

}
