/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import com.alibaba.fastjson.annotation.JSONField;

import io.swagger.annotations.ApiModel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Tag represents a repository tag
 */
@ApiModel(description = "Tag represents a repository tag")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Tag {
    @JSONField(name = "commit")
    private CommitMeta commit;

    @JSONField(name = "id")
    private String id;

    @JSONField(name = "name")
    private String name;

    @JSONField(name = "tarball_url")
    private String tarballUrl;

    @JSONField(name = "zipball_url")
    private String zipballUrl;

}
