/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.util.Date;

import org.nutz.json.JsonField;

import io.swagger.annotations.ApiModel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * TopicResponse for returning topics
 */
@ApiModel(description = "TopicResponse for returning topics")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TopicResponse {
    @JsonField("created")
    private Date created;

    @JsonField("id")
    private Long id;

    @JsonField("repo_count")
    private Long repoCount;

    @JsonField("topic_name")
    private String topicName;

    @JsonField("updated")
    private Date updated;

}
