/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.util.Date;

import org.nutz.json.JsonField;

import io.swagger.annotations.ApiModel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * TrackedTime worked time for an issue / pr
 */
@ApiModel(description = "TrackedTime worked time for an issue / pr")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TrackedTime {
    @JsonField("created")
    private Date created;

    @JsonField("id")
    private Long id;

    @JsonField("issue")
    private Issue issue;

    @JsonField("issue_id")
    private Long issueId;

    @JsonField("time")
    private Long time;

    @JsonField("user_id")
    private Long userId;

    @JsonField("user_name")
    private String userName;

}
