/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import org.nutz.json.JsonField;

import io.swagger.annotations.ApiModel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * UpdateFileOptions options for updating files Note: &#x60;author&#x60; and
 * &#x60;committer&#x60; are optional (if only one is given, it will be used for
 * the other, otherwise the authenticated user will be used)
 */
@ApiModel(
        description = "UpdateFileOptions options for updating files Note: `author` and `committer` are optional (if only one is given, it will be used for the other, otherwise the authenticated user will be used)")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class UpdateFileOptions {
    @JsonField("author")
    private Identity author;

    @JsonField("branch")
    private String branch;

    @JsonField("committer")
    private Identity committer;

    @JsonField("content")
    private String content;

    @JsonField("dates")
    private CommitDateOptions dates;

    @JsonField("from_path")
    private String fromPath;

    @JsonField("message")
    private String message;

    @JsonField("new_branch")
    private String newBranch;

    @JsonField("sha")
    private String sha;

}
