/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import org.nutz.json.JsonField;

import io.swagger.annotations.ApiModel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * UserHeatmapData represents the data needed to create a heatmap
 */
@ApiModel(description = "UserHeatmapData represents the data needed to create a heatmap")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class UserHeatmapData {
    @JsonField("contributions")
    private Long contributions;

    @JsonField("timestamp")
    private Integer timestamp;

}
