/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.util.Date;

import org.nutz.json.JsonField;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * User represents a user
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(of = "id")
public class User {
    @JsonField("avatar_url")
    private String avatarUrl;

    @JsonField("created")
    private Date created;

    @JsonField("email")
    private String email;

    @JsonField("full_name")
    private String fullName;

    @JsonField("id")
    private long id;

    @JsonField("is_admin")
    private boolean admin;

    @JsonField("language")
    private String language;

    @JsonField("last_login")
    private Date lastLogin;

    @JsonField("login")
    private String userName;

}
