/*
 * Gitea API. This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package com.kerbores.gitea.client.model;

import java.util.Date;

import org.nutz.json.JsonField;

import io.swagger.annotations.ApiModel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * WatchInfo represents an API watch status of one repository
 */
@ApiModel(description = "WatchInfo represents an API watch status of one repository")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class WatchInfo {
    @JsonField("created_at")
    private Date createdAt;

    @JsonField("ignored")
    private Boolean ignored;

    @JsonField("reason")
    private Object reason;

    @JsonField("repository_url")
    private String repositoryUrl;

    @JsonField("subscribed")
    private Boolean subscribed;

    @JsonField("url")
    private String url;

}
